# Generated by Django 3.1 on 2021-11-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.CharField(default='', max_length=200)),
                ('famous', models.CharField(default='', max_length=500)),
                ('payopt', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
