# Generated by Django 3.1 on 2021-11-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
