# Generated by Django 3.1 on 2021-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0002_package_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('Sr', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(default='', max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('availability', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
