# Generated by Django 3.1 on 2021-11-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0003_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.CharField(default='', max_length=500),
        ),
    ]
