# Generated by Django 3.1 on 2021-11-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0004_auto_20211113_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='contact',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
