# Generated by Django 3.1 on 2021-11-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0006_auto_20211114_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='package/'),
        ),
    ]
