# Generated by Django 3.1 on 2021-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0007_auto_20211115_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='content1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='package',
            name='content2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='package',
            name='content3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='package',
            name='contentimage1',
            field=models.ImageField(default=' ', upload_to='contentimage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='contentimage2',
            field=models.ImageField(default=' ', upload_to='contentimage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='contentimage3',
            field=models.ImageField(default=' ', upload_to='contentimage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hotel1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='hotelimage1',
            field=models.ImageField(default=' ', upload_to='hotelimage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hotelimage2',
            field=models.ImageField(default=' ', upload_to='hotelimage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hotelimage3',
            field=models.ImageField(default=' ', upload_to='hotelimage/'),
            preserve_default=False,
        ),
    ]
